### ISSUE TITLE
I'm still observing the MXC logo in the Geneva Explorer instead of Moonchain on the tab label. Below is the screenshot.

### ISSUE THREAD

**Issue by hairyf** [MXCzkEVM/blockscount-frontend#1]
I'm still observing the MXC logo in the Geneva Explorer instead of Moonchain on the tab label. Below is the screenshot.
https://geneva-explorer.moonchain.com/mapper

![Image](https://github.com/MXCzkEVM/explorer-frontend/assets/93600163/d7d5c581-8121-4136-8c0e-92df00999d98)

**Comment by hairyf** [comment]
I think this should be caused by caching. can you clear the cache and try again?

![Image](https://github.com/MXCzkEVM/explorer-frontend/assets/49724027/b7ed8d89-da10-4039-82af-1eff6671e1c0)

**Comment by SanghamitraBhowmick1993** [comment]
Working as expected!! 

![Image](https://github.com/MXCzkEVM/explorer-frontend/assets/93600163/991c8ecb-7405-4006-905a-cfa22734b040)
